### ISSUE TITLE
Error loadpheno()

### ISSUE THREAD

**Issue by Aranil** [MarkusZehner/rcm_archive#1]
https://github.com/MarkusZehner/rcm_archive/blob/2d593a6f94e0df28f17e6896ee86c276a872f9c1/rcm_archive/loadwd.py#L169

Hey Markus, 

i am running this code and getting Error:

import rcm_archive.RCM_DB as db
from rcm_archive import loadwd, db_structure

rcmarchive = db.RCMArchive(r'...\...\RCM')
catch_db = r'...\...\cachDB'

loadwd.loadpheno(filenames='Mais', station_id=13410, year=2018)

########
Traceback (most recent call last):
  File "F:/RCM/sarbian/xx_03_processing/python_modules/pulled_fromGitHub/rcm/xx_01/downloader.py", line 72, in <module>
    downloader()
  File "F:/RCM/sarbian/xx_03_processing/python_modules/pulled_fromGitHub/rcm/xx_01/downloader.py", line 67, in downloader
    loadwd.loadpheno(filenames='Mais', station_id=13410, year=2018)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\rcm_archive\loadwd.py", line 232, in loadpheno
    observations = client.get_observations(options)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\phenodata\dwd\pheno.py", line 178, in get_observations
    observations = self.query(partition=options['partition'], files=options['filename'])
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\phenodata\dwd\pheno.py", line 273, in query
    paths = self.scan_files(partition, include=files, field='url')
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\phenodata\dwd\pheno.py", line 443, in scan_files
    exclude_base=['PH_Beschreibung', 'Spezifizierung', 'PH_.+_Notiz'],
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\phenodata\ftp.py", line 182, in scan_files
    child_items = self.list_plus(url)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\phenodata\ftp.py", line 108, in list_plus
    return self.cache.meta.get_or_create(key, lambda: self.list_plus_real(url))
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\cache\region.py", line 962, in get_or_create
    async_creator,
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\lock.py", line 185, in __enter__
    return self._enter()
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\lock.py", line 87, in _enter
    value = value_fn()
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\cache\region.py", line 902, in get_value
    value = self.backend.get(key)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\cache\backends\file.py", line 223, in get
    with self._dbm_file(False) as dbm:
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\cache\backends\file.py", line 217, in _dbm_file
    with self._use_rw_lock(write):
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\cache\backends\file.py", line 212, in _use_rw_lock
    with self._rw_lock.read():
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\cache\backends\file.py", line 332, in read
    self.acquire_read_lock(True)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\cache\backends\file.py", line 414, in acquire_read_lock
    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\util\langhelpers.py", line 69, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\se56rij\Documents\anaconda3\envs\claaspy36_git\lib\site-packages\dogpile\cache\backends\file.py", line 405, in _module
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

Process finished with exit code 1
########

i am working on win10

Thanks,
Lina

**Comment by MarkusZehner** [comment]
fcntl wont work on windows, so maybe use virtual machine on win
